site_name: seebuoy
site_description: seebuoy, ocean data, wave data, python, buoy data

nav:
    - Home: index.md
    - NDBC: ndbc.md
    - Install: install.md
    - API: api.md
    - Contributing: contributing.md

theme:
  name: 'material'
  logo: 'img/icon-white.png'
  favicon: 'img/favicon.png'

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings

repo_name: nickc1/seebuoy
repo_url: https://github.com/nickc1/seebuoy
edit_uri: ''

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
